sections:
  examkpleSection1:
    title: "Section1"
    fields:
      os:
        title: "Welches OS"
        type: "select"
        desc: "Hier eine Beschreibung"
        option:
          0: "Windows"
          1: "Linux"
          2: "OSX"
        required: true
        outerClass: "col-md-6"
      zustand:
        title: "Wie geht es Dir heute?"
        type: "text"
        desc: "Kurzer Text über deinen Zustandg"
        required: true
        outerClass: "col-md-6"
  examkpleSection2:
    title: "Section2"
    fields:
      about:
        title: "Deine Geschichte"
        type: "textarea"
        outerClass: "col-md-12"
      transport:
        title: "Velotransport"
        type: "checkbox"
        option:
          0: "Ich kann mein Velo nicht selbst transportieren"
        required: false
        outerClass: "col-md-12"

        
  