name-template: '$RESOLVED_VERSION 🌈'
tag-template: '$RESOLVED_VERSION'
categories:
    - title: '🚀 Features'
      labels:
          - 'new feature'
    - title: 'Enhancements'
      labels:
          - 'enhancement'
          - 'translation'
          - 'style'
    - title: '🐛 Bug Fixes'
      labels:
          - 'bug'
          - 'fix'
          - 'bugfix'
    - title: '⬆️ Dependencies'
      labels:
        - 'dependencies'
    - title: '🧰 Maintenance'
      label: 'chore'
exclude-labels:
    - 'duplicate'
    - 'invalid'
    - 'wontfix'
    - 'release'
exclude-contributors:
    - 'dependabot'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&`#@'
version-resolver:
    minor:
        labels:
            - 'new feature'
            - 'release'
    patch:
        labels:
            - 'enhancement'
            - 'bug'
            - 'translation'
            - 'style'
    default: patch
template: |

    $CHANGES
    
    Involved in this release: $CONTRIBUTORS - thank you!