changelog:
  exclude:
    authors:
      - dependabot
  categories:
    - title: Breaking Changes
      labels:
        - 'breaking change'
    - title: Fixed Bugs
      labels:
        - bug
    - title: New Features
      labels:
        - 'new feature'
    - title: Enhancements
      labels:
        - enhancement
    - title: Refactoring
      labels:
        - refactor
    - title: Others
      labels:
        - "*"